/*
Fabric Orchestrator API

Testing SlicesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SlicesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SlicesAPIService SlicesCreatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SlicesAPI.SlicesCreatePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesCreatesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SlicesAPI.SlicesCreatesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesDeleteDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SlicesAPI.SlicesDeleteDelete(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesDeleteSliceIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sliceId string

		resp, httpRes, err := apiClient.SlicesAPI.SlicesDeleteSliceIdDelete(context.Background(), sliceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SlicesAPI.SlicesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesModifySliceIdAcceptPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sliceId string

		resp, httpRes, err := apiClient.SlicesAPI.SlicesModifySliceIdAcceptPost(context.Background(), sliceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesModifySliceIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sliceId string

		resp, httpRes, err := apiClient.SlicesAPI.SlicesModifySliceIdPut(context.Background(), sliceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesRenewSliceIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sliceId string

		resp, httpRes, err := apiClient.SlicesAPI.SlicesRenewSliceIdPost(context.Background(), sliceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SlicesAPIService SlicesSliceIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sliceId string

		resp, httpRes, err := apiClient.SlicesAPI.SlicesSliceIdGet(context.Background(), sliceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
