/*
Fabric Orchestrator API

Testing PoasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CSC478-WCU/fabric-orchestrator-go-client"
)

func Test_openapi_PoasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PoasAPIService PoasCreateSliverIdPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sliverId string

		resp, httpRes, err := apiClient.PoasAPI.PoasCreateSliverIdPost(context.Background(), sliverId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoasAPIService PoasGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PoasAPI.PoasGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PoasAPIService PoasPoaIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var poaId string

		resp, httpRes, err := apiClient.PoasAPI.PoasPoaIdGet(context.Background(), poaId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
