/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status403ForbiddenErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status403ForbiddenErrors{}

// Status403ForbiddenErrors struct for Status403ForbiddenErrors
type Status403ForbiddenErrors struct {
	Message *string `json:"message,omitempty"`
	Details *string `json:"details,omitempty"`
}

// NewStatus403ForbiddenErrors instantiates a new Status403ForbiddenErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus403ForbiddenErrors() *Status403ForbiddenErrors {
	this := Status403ForbiddenErrors{}
	var message string = "Forbidden"
	this.Message = &message
	return &this
}

// NewStatus403ForbiddenErrorsWithDefaults instantiates a new Status403ForbiddenErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus403ForbiddenErrorsWithDefaults() *Status403ForbiddenErrors {
	this := Status403ForbiddenErrors{}
	var message string = "Forbidden"
	this.Message = &message
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Status403ForbiddenErrors) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status403ForbiddenErrors) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Status403ForbiddenErrors) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Status403ForbiddenErrors) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *Status403ForbiddenErrors) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status403ForbiddenErrors) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *Status403ForbiddenErrors) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *Status403ForbiddenErrors) SetDetails(v string) {
	o.Details = &v
}

func (o Status403ForbiddenErrors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status403ForbiddenErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableStatus403ForbiddenErrors struct {
	value *Status403ForbiddenErrors
	isSet bool
}

func (v NullableStatus403ForbiddenErrors) Get() *Status403ForbiddenErrors {
	return v.value
}

func (v *NullableStatus403ForbiddenErrors) Set(val *Status403ForbiddenErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus403ForbiddenErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus403ForbiddenErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus403ForbiddenErrors(val *Status403ForbiddenErrors) *NullableStatus403ForbiddenErrors {
	return &NullableStatus403ForbiddenErrors{value: val, isSet: true}
}

func (v NullableStatus403ForbiddenErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus403ForbiddenErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


