/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status401UnauthorizedErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status401UnauthorizedErrors{}

// Status401UnauthorizedErrors struct for Status401UnauthorizedErrors
type Status401UnauthorizedErrors struct {
	Message *string `json:"message,omitempty"`
	Details *string `json:"details,omitempty"`
}

// NewStatus401UnauthorizedErrors instantiates a new Status401UnauthorizedErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus401UnauthorizedErrors() *Status401UnauthorizedErrors {
	this := Status401UnauthorizedErrors{}
	var message string = "Unauthorized"
	this.Message = &message
	return &this
}

// NewStatus401UnauthorizedErrorsWithDefaults instantiates a new Status401UnauthorizedErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus401UnauthorizedErrorsWithDefaults() *Status401UnauthorizedErrors {
	this := Status401UnauthorizedErrors{}
	var message string = "Unauthorized"
	this.Message = &message
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Status401UnauthorizedErrors) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status401UnauthorizedErrors) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Status401UnauthorizedErrors) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Status401UnauthorizedErrors) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *Status401UnauthorizedErrors) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status401UnauthorizedErrors) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *Status401UnauthorizedErrors) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *Status401UnauthorizedErrors) SetDetails(v string) {
	o.Details = &v
}

func (o Status401UnauthorizedErrors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status401UnauthorizedErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableStatus401UnauthorizedErrors struct {
	value *Status401UnauthorizedErrors
	isSet bool
}

func (v NullableStatus401UnauthorizedErrors) Get() *Status401UnauthorizedErrors {
	return v.value
}

func (v *NullableStatus401UnauthorizedErrors) Set(val *Status401UnauthorizedErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus401UnauthorizedErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus401UnauthorizedErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus401UnauthorizedErrors(val *Status401UnauthorizedErrors) *NullableStatus401UnauthorizedErrors {
	return &NullableStatus401UnauthorizedErrors{value: val, isSet: true}
}

func (v NullableStatus401UnauthorizedErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus401UnauthorizedErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


