/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SliceDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SliceDetails{}

// SliceDetails struct for SliceDetails
type SliceDetails struct {
	Size *int32 `json:"size,omitempty"`
	Status *int32 `json:"status,omitempty"`
	Type *string `json:"type,omitempty"`
	Data []Slice `json:"data,omitempty"`
}

// NewSliceDetails instantiates a new SliceDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSliceDetails() *SliceDetails {
	this := SliceDetails{}
	var size int32 = 1
	this.Size = &size
	var status int32 = 200
	this.Status = &status
	return &this
}

// NewSliceDetailsWithDefaults instantiates a new SliceDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSliceDetailsWithDefaults() *SliceDetails {
	this := SliceDetails{}
	var size int32 = 1
	this.Size = &size
	var status int32 = 200
	this.Status = &status
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *SliceDetails) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SliceDetails) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *SliceDetails) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *SliceDetails) SetSize(v int32) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SliceDetails) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SliceDetails) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SliceDetails) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *SliceDetails) SetStatus(v int32) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SliceDetails) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SliceDetails) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SliceDetails) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SliceDetails) SetType(v string) {
	o.Type = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SliceDetails) GetData() []Slice {
	if o == nil || IsNil(o.Data) {
		var ret []Slice
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SliceDetails) GetDataOk() ([]Slice, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SliceDetails) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Slice and assigns it to the Data field.
func (o *SliceDetails) SetData(v []Slice) {
	o.Data = v
}

func (o SliceDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SliceDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSliceDetails struct {
	value *SliceDetails
	isSet bool
}

func (v NullableSliceDetails) Get() *SliceDetails {
	return v.value
}

func (v *NullableSliceDetails) Set(val *SliceDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableSliceDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableSliceDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSliceDetails(val *SliceDetails) *NullableSliceDetails {
	return &NullableSliceDetails{value: val, isSet: true}
}

func (v NullableSliceDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSliceDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


