/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status200OkPaginated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status200OkPaginated{}

// Status200OkPaginated struct for Status200OkPaginated
type Status200OkPaginated struct {
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Size *int32 `json:"size,omitempty"`
	Status *int32 `json:"status,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewStatus200OkPaginated instantiates a new Status200OkPaginated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus200OkPaginated() *Status200OkPaginated {
	this := Status200OkPaginated{}
	var status int32 = 200
	this.Status = &status
	return &this
}

// NewStatus200OkPaginatedWithDefaults instantiates a new Status200OkPaginated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus200OkPaginatedWithDefaults() *Status200OkPaginated {
	this := Status200OkPaginated{}
	var status int32 = 200
	this.Status = &status
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *Status200OkPaginated) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkPaginated) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *Status200OkPaginated) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *Status200OkPaginated) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *Status200OkPaginated) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkPaginated) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *Status200OkPaginated) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *Status200OkPaginated) SetOffset(v int32) {
	o.Offset = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Status200OkPaginated) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkPaginated) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Status200OkPaginated) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *Status200OkPaginated) SetSize(v int32) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Status200OkPaginated) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkPaginated) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Status200OkPaginated) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *Status200OkPaginated) SetStatus(v int32) {
	o.Status = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *Status200OkPaginated) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkPaginated) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *Status200OkPaginated) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *Status200OkPaginated) SetTotal(v int32) {
	o.Total = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Status200OkPaginated) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkPaginated) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Status200OkPaginated) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Status200OkPaginated) SetType(v string) {
	o.Type = &v
}

func (o Status200OkPaginated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status200OkPaginated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableStatus200OkPaginated struct {
	value *Status200OkPaginated
	isSet bool
}

func (v NullableStatus200OkPaginated) Get() *Status200OkPaginated {
	return v.value
}

func (v *NullableStatus200OkPaginated) Set(val *Status200OkPaginated) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus200OkPaginated) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus200OkPaginated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus200OkPaginated(val *Status200OkPaginated) *NullableStatus200OkPaginated {
	return &NullableStatus200OkPaginated{value: val, isSet: true}
}

func (v NullableStatus200OkPaginated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus200OkPaginated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


