/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status200OkNoContentData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status200OkNoContentData{}

// Status200OkNoContentData struct for Status200OkNoContentData
type Status200OkNoContentData struct {
	Message *string `json:"message,omitempty"`
	Details *string `json:"details,omitempty"`
}

// NewStatus200OkNoContentData instantiates a new Status200OkNoContentData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus200OkNoContentData() *Status200OkNoContentData {
	this := Status200OkNoContentData{}
	var message string = "No Content"
	this.Message = &message
	return &this
}

// NewStatus200OkNoContentDataWithDefaults instantiates a new Status200OkNoContentData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus200OkNoContentDataWithDefaults() *Status200OkNoContentData {
	this := Status200OkNoContentData{}
	var message string = "No Content"
	this.Message = &message
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Status200OkNoContentData) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkNoContentData) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Status200OkNoContentData) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Status200OkNoContentData) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *Status200OkNoContentData) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkNoContentData) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *Status200OkNoContentData) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *Status200OkNoContentData) SetDetails(v string) {
	o.Details = &v
}

func (o Status200OkNoContentData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status200OkNoContentData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableStatus200OkNoContentData struct {
	value *Status200OkNoContentData
	isSet bool
}

func (v NullableStatus200OkNoContentData) Get() *Status200OkNoContentData {
	return v.value
}

func (v *NullableStatus200OkNoContentData) Set(val *Status200OkNoContentData) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus200OkNoContentData) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus200OkNoContentData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus200OkNoContentData(val *Status200OkNoContentData) *NullableStatus200OkNoContentData {
	return &NullableStatus200OkNoContentData{value: val, isSet: true}
}

func (v NullableStatus200OkNoContentData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus200OkNoContentData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


