/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status200OkNoContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status200OkNoContent{}

// Status200OkNoContent struct for Status200OkNoContent
type Status200OkNoContent struct {
	Data []Status200OkNoContentData `json:"data,omitempty"`
	Type *string `json:"type,omitempty"`
	Size *int32 `json:"size,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewStatus200OkNoContent instantiates a new Status200OkNoContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus200OkNoContent() *Status200OkNoContent {
	this := Status200OkNoContent{}
	var type_ string = "no_content"
	this.Type = &type_
	var size int32 = 1
	this.Size = &size
	var status int32 = 200
	this.Status = &status
	return &this
}

// NewStatus200OkNoContentWithDefaults instantiates a new Status200OkNoContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus200OkNoContentWithDefaults() *Status200OkNoContent {
	this := Status200OkNoContent{}
	var type_ string = "no_content"
	this.Type = &type_
	var size int32 = 1
	this.Size = &size
	var status int32 = 200
	this.Status = &status
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Status200OkNoContent) GetData() []Status200OkNoContentData {
	if o == nil || IsNil(o.Data) {
		var ret []Status200OkNoContentData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkNoContent) GetDataOk() ([]Status200OkNoContentData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Status200OkNoContent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Status200OkNoContentData and assigns it to the Data field.
func (o *Status200OkNoContent) SetData(v []Status200OkNoContentData) {
	o.Data = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Status200OkNoContent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkNoContent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Status200OkNoContent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Status200OkNoContent) SetType(v string) {
	o.Type = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Status200OkNoContent) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkNoContent) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Status200OkNoContent) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *Status200OkNoContent) SetSize(v int32) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Status200OkNoContent) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status200OkNoContent) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Status200OkNoContent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *Status200OkNoContent) SetStatus(v int32) {
	o.Status = &v
}

func (o Status200OkNoContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status200OkNoContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableStatus200OkNoContent struct {
	value *Status200OkNoContent
	isSet bool
}

func (v NullableStatus200OkNoContent) Get() *Status200OkNoContent {
	return v.value
}

func (v *NullableStatus200OkNoContent) Set(val *Status200OkNoContent) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus200OkNoContent) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus200OkNoContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus200OkNoContent(val *Status200OkNoContent) *NullableStatus200OkNoContent {
	return &NullableStatus200OkNoContent{value: val, isSet: true}
}

func (v NullableStatus200OkNoContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus200OkNoContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


