/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status500InternalServerErrorErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status500InternalServerErrorErrors{}

// Status500InternalServerErrorErrors struct for Status500InternalServerErrorErrors
type Status500InternalServerErrorErrors struct {
	Message *string `json:"message,omitempty"`
	Details *string `json:"details,omitempty"`
}

// NewStatus500InternalServerErrorErrors instantiates a new Status500InternalServerErrorErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus500InternalServerErrorErrors() *Status500InternalServerErrorErrors {
	this := Status500InternalServerErrorErrors{}
	var message string = "Internal Server Error"
	this.Message = &message
	return &this
}

// NewStatus500InternalServerErrorErrorsWithDefaults instantiates a new Status500InternalServerErrorErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus500InternalServerErrorErrorsWithDefaults() *Status500InternalServerErrorErrors {
	this := Status500InternalServerErrorErrors{}
	var message string = "Internal Server Error"
	this.Message = &message
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Status500InternalServerErrorErrors) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status500InternalServerErrorErrors) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Status500InternalServerErrorErrors) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Status500InternalServerErrorErrors) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *Status500InternalServerErrorErrors) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status500InternalServerErrorErrors) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *Status500InternalServerErrorErrors) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *Status500InternalServerErrorErrors) SetDetails(v string) {
	o.Details = &v
}

func (o Status500InternalServerErrorErrors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status500InternalServerErrorErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableStatus500InternalServerErrorErrors struct {
	value *Status500InternalServerErrorErrors
	isSet bool
}

func (v NullableStatus500InternalServerErrorErrors) Get() *Status500InternalServerErrorErrors {
	return v.value
}

func (v *NullableStatus500InternalServerErrorErrors) Set(val *Status500InternalServerErrorErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus500InternalServerErrorErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus500InternalServerErrorErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus500InternalServerErrorErrors(val *Status500InternalServerErrorErrors) *NullableStatus500InternalServerErrorErrors {
	return &NullableStatus500InternalServerErrorErrors{value: val, isSet: true}
}

func (v NullableStatus500InternalServerErrorErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus500InternalServerErrorErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


