/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status400BadRequestErrors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status400BadRequestErrors{}

// Status400BadRequestErrors struct for Status400BadRequestErrors
type Status400BadRequestErrors struct {
	Message *string `json:"message,omitempty"`
	Details *string `json:"details,omitempty"`
	Type *string `json:"type,omitempty"`
	Size *int32 `json:"size,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewStatus400BadRequestErrors instantiates a new Status400BadRequestErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus400BadRequestErrors() *Status400BadRequestErrors {
	this := Status400BadRequestErrors{}
	var message string = "Bad Request"
	this.Message = &message
	var type_ string = "error"
	this.Type = &type_
	var size int32 = 1
	this.Size = &size
	var status int32 = 400
	this.Status = &status
	return &this
}

// NewStatus400BadRequestErrorsWithDefaults instantiates a new Status400BadRequestErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus400BadRequestErrorsWithDefaults() *Status400BadRequestErrors {
	this := Status400BadRequestErrors{}
	var message string = "Bad Request"
	this.Message = &message
	var type_ string = "error"
	this.Type = &type_
	var size int32 = 1
	this.Size = &size
	var status int32 = 400
	this.Status = &status
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Status400BadRequestErrors) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status400BadRequestErrors) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Status400BadRequestErrors) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Status400BadRequestErrors) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *Status400BadRequestErrors) GetDetails() string {
	if o == nil || IsNil(o.Details) {
		var ret string
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status400BadRequestErrors) GetDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *Status400BadRequestErrors) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given string and assigns it to the Details field.
func (o *Status400BadRequestErrors) SetDetails(v string) {
	o.Details = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Status400BadRequestErrors) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status400BadRequestErrors) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Status400BadRequestErrors) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Status400BadRequestErrors) SetType(v string) {
	o.Type = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Status400BadRequestErrors) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status400BadRequestErrors) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Status400BadRequestErrors) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *Status400BadRequestErrors) SetSize(v int32) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Status400BadRequestErrors) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status400BadRequestErrors) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Status400BadRequestErrors) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *Status400BadRequestErrors) SetStatus(v int32) {
	o.Status = &v
}

func (o Status400BadRequestErrors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status400BadRequestErrors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableStatus400BadRequestErrors struct {
	value *Status400BadRequestErrors
	isSet bool
}

func (v NullableStatus400BadRequestErrors) Get() *Status400BadRequestErrors {
	return v.value
}

func (v *NullableStatus400BadRequestErrors) Set(val *Status400BadRequestErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus400BadRequestErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus400BadRequestErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus400BadRequestErrors(val *Status400BadRequestErrors) *NullableStatus400BadRequestErrors {
	return &NullableStatus400BadRequestErrors{value: val, isSet: true}
}

func (v NullableStatus400BadRequestErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus400BadRequestErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


