/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Status500InternalServerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Status500InternalServerError{}

// Status500InternalServerError struct for Status500InternalServerError
type Status500InternalServerError struct {
	Errors []Status500InternalServerErrorErrors `json:"errors,omitempty"`
	Type *string `json:"type,omitempty"`
	Size *int32 `json:"size,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewStatus500InternalServerError instantiates a new Status500InternalServerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus500InternalServerError() *Status500InternalServerError {
	this := Status500InternalServerError{}
	var type_ string = "error"
	this.Type = &type_
	var size int32 = 1
	this.Size = &size
	var status int32 = 500
	this.Status = &status
	return &this
}

// NewStatus500InternalServerErrorWithDefaults instantiates a new Status500InternalServerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus500InternalServerErrorWithDefaults() *Status500InternalServerError {
	this := Status500InternalServerError{}
	var type_ string = "error"
	this.Type = &type_
	var size int32 = 1
	this.Size = &size
	var status int32 = 500
	this.Status = &status
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Status500InternalServerError) GetErrors() []Status500InternalServerErrorErrors {
	if o == nil || IsNil(o.Errors) {
		var ret []Status500InternalServerErrorErrors
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status500InternalServerError) GetErrorsOk() ([]Status500InternalServerErrorErrors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Status500InternalServerError) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Status500InternalServerErrorErrors and assigns it to the Errors field.
func (o *Status500InternalServerError) SetErrors(v []Status500InternalServerErrorErrors) {
	o.Errors = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Status500InternalServerError) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status500InternalServerError) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Status500InternalServerError) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Status500InternalServerError) SetType(v string) {
	o.Type = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Status500InternalServerError) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status500InternalServerError) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Status500InternalServerError) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *Status500InternalServerError) SetSize(v int32) {
	o.Size = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Status500InternalServerError) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Status500InternalServerError) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Status500InternalServerError) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *Status500InternalServerError) SetStatus(v int32) {
	o.Status = &v
}

func (o Status500InternalServerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Status500InternalServerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableStatus500InternalServerError struct {
	value *Status500InternalServerError
	isSet bool
}

func (v NullableStatus500InternalServerError) Get() *Status500InternalServerError {
	return v.value
}

func (v *NullableStatus500InternalServerError) Set(val *Status500InternalServerError) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus500InternalServerError) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus500InternalServerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus500InternalServerError(val *Status500InternalServerError) *NullableStatus500InternalServerError {
	return &NullableStatus500InternalServerError{value: val, isSet: true}
}

func (v NullableStatus500InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus500InternalServerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


