/*
Fabric Orchestrator API

This is Fabric Orchestrator API

API version: 1.0.1
Contact: kthare10@unc.edu
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PoaPostDataKeys type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoaPostDataKeys{}

// PoaPostDataKeys struct for PoaPostDataKeys
type PoaPostDataKeys struct {
	Key string `json:"key"`
	Comment string `json:"comment"`
}

type _PoaPostDataKeys PoaPostDataKeys

// NewPoaPostDataKeys instantiates a new PoaPostDataKeys object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoaPostDataKeys(key string, comment string) *PoaPostDataKeys {
	this := PoaPostDataKeys{}
	this.Key = key
	this.Comment = comment
	return &this
}

// NewPoaPostDataKeysWithDefaults instantiates a new PoaPostDataKeys object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoaPostDataKeysWithDefaults() *PoaPostDataKeys {
	this := PoaPostDataKeys{}
	return &this
}

// GetKey returns the Key field value
func (o *PoaPostDataKeys) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PoaPostDataKeys) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PoaPostDataKeys) SetKey(v string) {
	o.Key = v
}

// GetComment returns the Comment field value
func (o *PoaPostDataKeys) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *PoaPostDataKeys) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *PoaPostDataKeys) SetComment(v string) {
	o.Comment = v
}

func (o PoaPostDataKeys) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoaPostDataKeys) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["comment"] = o.Comment
	return toSerialize, nil
}

func (o *PoaPostDataKeys) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"comment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoaPostDataKeys := _PoaPostDataKeys{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoaPostDataKeys)

	if err != nil {
		return err
	}

	*o = PoaPostDataKeys(varPoaPostDataKeys)

	return err
}

type NullablePoaPostDataKeys struct {
	value *PoaPostDataKeys
	isSet bool
}

func (v NullablePoaPostDataKeys) Get() *PoaPostDataKeys {
	return v.value
}

func (v *NullablePoaPostDataKeys) Set(val *PoaPostDataKeys) {
	v.value = val
	v.isSet = true
}

func (v NullablePoaPostDataKeys) IsSet() bool {
	return v.isSet
}

func (v *NullablePoaPostDataKeys) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoaPostDataKeys(val *PoaPostDataKeys) *NullablePoaPostDataKeys {
	return &NullablePoaPostDataKeys{value: val, isSet: true}
}

func (v NullablePoaPostDataKeys) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoaPostDataKeys) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


